# Generated by Django 4.0.4 on 2022-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_application_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Телефон'),
        ),
    ]
